DROP TABLE md_user_keuangan;
CREATE TABLE `md_user_keuangan` ( `USER_MUK` INT(12) NOT NULL , `TAGIHAN_MUK` INT(12) NOT NULL , `DEPT_MUK` VARCHAR(10) NOT NULL , `CREATED_MUK` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , INDEX (`USER_MUK`), INDEX (`TAGIHAN_MUK`), INDEX (`DEPT_MUK`)) ENGINE = InnoDB;

ALTER TABLE `md_user_keuangan` ADD FOREIGN KEY (`USER_MUK`) REFERENCES `md_user`(`ID_USER`) ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE `md_user_keuangan` ADD FOREIGN KEY (`TAGIHAN_MUK`) REFERENCES `keu_tagihan`(`ID_TAG`) ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE `md_user_keuangan` ADD FOREIGN KEY (`DEPT_MUK`) REFERENCES `md_departemen`(`ID_DEPT`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `md_user_keuangan` ADD UNIQUE( `USER_MUK`, `TAGIHAN_MUK`, `DEPT_MUK`);


ALTER TABLE `md_pegawai` ADD `NOHP1_PEG` INT(12) NULL DEFAULT NULL AFTER `NOHP_PEG`;
ALTER TABLE `md_pegawai` CHANGE `NOHP_PEG` `NOHP_PEG` BIGINT(12) NULL DEFAULT NULL;
ALTER TABLE `md_pegawai` CHANGE `NOHP1_PEG` `NOHP1_PEG` BIGINT(12) NULL DEFAULT NULL;
