ALTER TABLE `pu_jadwal` ADD `JK_PUJ` VARCHAR(4) NULL DEFAULT NULL AFTER `CAWU_PUJ`, ADD INDEX (`JK_PUJ`);
ALTER TABLE `pu_jadwal` ADD FOREIGN KEY (`JK_PUJ`) REFERENCES `simapes_2`.`md_jenis_kelamin`(`ID_JK`) ON DELETE RESTRICT ON UPDATE CASCADE;
UPDATE `pu_jadwal` SET `JK_PUJ` = 'L' WHERE `pu_jadwal`.`ID_PUJ` = 8;
UPDATE `pu_jadwal` SET `JK_PUJ` = 'L' WHERE `pu_jadwal`.`ID_PUJ` = 9;
ALTER TABLE `simapes_2`.`pu_jadwal` 
DROP INDEX `TIPE_PUJ` ,
ADD UNIQUE INDEX `TIPE_PUJ` (`TIPE_PUJ` ASC, `TANGGAL_PUJ` ASC, `JAM_MULAI_PUJ` ASC, `JAM_SELESAI_PUJ` ASC, `JK_PUJ` ASC);
